version: "3.2"
services:
  ic-db:
    container_name: ${DB_CONTAINER_NAME}
    command: -c ssl=off
    image: ${POSTGRES_IMAGE}
    environment:
      ALLOW_IP_RANGE: 0.0.0.0/0
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DBNAME: ${POSTGRES_DBNAME}
      POSTGRES_DB: ${POSTGRES_DBNAME}
      POSTGRES_PORT: ${POSTGRES_PORT}
      # POSTGRES_MULTIPLE_EXTENSIONS: postgis,hstore,postgis_topology,postgis_raster,pgrouting
    volumes:
      - ./dev/db/local:/var/lib/postgresql/12/main
      # - ${POSTGRES_SSL_PATH}/cert.pem:/var/lib/postgresql/server.crt
      # - ${POSTGRES_SSL_PATH}/key.pem:/var/lib/postgresql/server.key
      # - ./db/postgres/docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
    ports:
      - "0.0.0.0:${DB_EXTERIOR_PORT}:${POSTGRES_PORT}"
    restart: on-failure
    healthcheck:
      test: "exit 0"
